spaceRace: spaceRace.o raster.o render.o sprites.o model.o events.o font.o rast_asm.o
	cc68x -g spaceRace.o raster.o render.o sprites.o model.o events.o font.o rast_asm.o -o spaceRace

spaceRace.o: spaceRace.c spaceRace.h
	cc68x -g -c spaceRace.c

raster.o: raster.c raster.h const.h
	cc68x -g -c raster.c

render.o: render.c render.h const.h
	cc68x -g -c render.c

sprites.o: sprites.c sprites.h const.h
	cc68x -g -c sprites.c

model.o: model.c model.h const.h
	cc68x -g -c model.c

events.o: events.c events.h const.h
	cc68x -g -c events.c

font.o: font.c font.h
	cc68x -g -c font.c

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s
	