test: tstModel.o raster.o sprites.o model.o events.o font.o rast_asm.o
	cc68x -g tstModel.o raster.o sprites.o model.o events.o font.o rast_asm.o -o spcRace

tstModel.o: tstModel.c const.h
	cc68x -g -c -v tstModel.c

raster.o: raster.c raster.h const.h
	cc68x -g -c raster.c

sprites.o: sprites.c sprites.h const.h
	cc68x -g -c sprites.c

model.o: model.c model.h const.h
	cc68x -g -c -v model.c

events.o: events.c events.h const.h
	cc68x -g -c events.c
	
font.o: font.c font.h
	cc68x -g -c font.c

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s
	