tstPSG: tstPSG.o psg.o effects.o music.o
	cc68x -g tstPSG.o psg.o effects.o music.o -o tstPSG

tstPSG.o: tstPSG.c 
	cc68x -g -c tstPSG.c

psg.o: psg.c psg.h
	cc68x -g -c psg.c

effects.o: effects.c effects.h
	cc68x -g -c effects.c

music.o: music.c music.h
	cc68x -g -c music.c

render.o: render.c render.h 
	cc68x -g -c render.c

raster.o: raster.c raster.h const.h
	cc68x -g -c raster.c

sprites.o: sprites.c sprites.h const.h
	cc68x -g -c sprites.c

model.o: model.c model.h const.h
	cc68x -g -c model.c

events.o: events.c events.h const.h
	cc68x -g -c events.c
	
font.o: font.c font.h
	cc68x -g -c font.c

clearG.o: clearG.s clearG.h
	gen -D -L2 clearG.s

clearQK.o: clearQK.s clearQK.h
	gen -D -L2 clearQK.s

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s
	