tst_rast: tst_rast.o raster.o rast_asm.o sprites.o font.o
	cc68x -g tst_rast.o raster.o sprites.o rast_asm.o font.o -o tst_rast

tst_rast.o: tst_rast.c raster.h const.h 
	cc68x -g -c tst_rast.c

raster.o: raster.c raster.h const.h font.h
	cc68x -g -c raster.c

font.o: font.c font.h
	cc68x -g -c font.c

sprites.o: sprites.c sprites.h const.h
	cc68x -g -c sprites.c

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s
	