tst_rast: tst_rast.o raster.o rast_asm.o sprites.o
	cc68x -g tst_rast.o raster.o sprites.o rast_asm.o -o tst_rast

tst_rast.o: tst_rast.c raster.h
	cc68x -g -c tst_rast.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c

sprites.o: sprites.c sprites.h
	cc68x -g -c sprites.c

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s
