tst_rast: tst_rast.o raster.o rast_asm.o sprites.o background.o
	cc68x -g tst_rast.o raster.o sprites.o rast_asm.o background.o -o tst_rast

tst_rast.o: tst_rast.c raster.h const.h background.h
	cc68x -g -c tst_rast.c

background.o: background.c background.h 
	cc68x -g -c background.c

raster.o: raster.c raster.h const.h
	cc68x -g -c raster.c

sprites.o: sprites.c sprites.h const.h
	cc68x -g -c sprites.c

model.o: model.c model.h const.h
	cc68x -g -c model.c

events.o: events.c events.h const.h
	cc68x -g -c events.c

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s
	